import sys
import json
import time
import random
import requests
import os 
from typing import Dict, Any, Optional, List

# --- Configuration & Key Loading ---

EVENT_DELIMITER = "------------------------------------------------"
MAX_RETRIES = 5
BASE_DELAY = 1.0 # seconds

def load_api_key() -> str:
    """
    Loads the Gemini API key from the specified path: 
    %USERPROFILE%/KeyVault/config.json -> gemini.api_key
    """
    # Use os.path.expanduser('~') for cross-platform compatibility with the home directory
    home_dir = os.path.expanduser('~')
    config_path = os.path.join(home_dir, 'KeyVault', 'config.json')

    print(f"[*] Attempting to load configuration from: {config_path}", file=sys.stderr)

    try:
        with open(config_path, 'r') as f:
            config = json.load(f)
            # Safely access the nested API key
            key = config.get('gemini', {}).get('api_key')
            
            if key:
                print("[*] Gemini API Key loaded successfully from config file.", file=sys.stderr)
                return key
            else:
                print("[CRITICAL] 'gemini.api_key' key not found in the config file.", file=sys.stderr)
                return ""
    
    except FileNotFoundError:
        print(f"[CRITICAL] Configuration file not found at: {config_path}", file=sys.stderr)
        return ""
    except json.JSONDecodeError:
        print(f"[CRITICAL] Failed to parse config.json. Check file format.", file=sys.stderr)
        return ""
    except Exception as e:
        print(f"[CRITICAL] Unexpected error during key loading: {e}", file=sys.stderr)
        return ""

# Load the API Key once at startup
API_KEY = load_api_key() 
GEMINI_MODEL = "gemini-2.5-flash-preview-09-2025"
API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent?key={API_KEY}"

# --- Utility: Exponential Backoff (Gemini API Wrapper) ---

def call_gemini_api(payload: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Handles API retries using exponential backoff for the Gemini API call."""
    # Check if API_KEY is set before proceeding
    if not API_KEY:
        print("[CRITICAL] API Key is missing. Cannot call Gemini API. Ensure the config file exists and contains 'gemini.api_key'.", file=sys.stderr)
        return None
        
    headers = {
        'Content-Type': 'application/json'
    }
    
    for attempt in range(MAX_RETRIES):
        try:
            response = requests.post(API_URL, headers=headers, json=payload, timeout=30)
            response.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)
            return response.json()
        except requests.exceptions.HTTPError as e:
            # Handle specific API errors like 429 (Rate Limit) or the 403 (Forbidden)
            if response.status_code == 429 and attempt < MAX_RETRIES - 1:
                delay = BASE_DELAY * (2 ** attempt) + random.uniform(0, 1)
                print(f"[ERROR] Rate limited (429) on attempt {attempt + 1}. Retrying in {delay:.2f}s.", file=sys.stderr)
                time.sleep(delay)
                continue
            else:
                print(f"[CRITICAL] HTTP Error after {attempt + 1} attempts or non-recoverable error ({response.status_code}): {e}", file=sys.stderr)
                return None
        except requests.exceptions.RequestException as e:
            if attempt < MAX_RETRIES - 1:
                delay = BASE_DELAY * (2 ** attempt) + random.uniform(0, 1)
                print(f"[ERROR] API call failed on attempt {attempt + 1}. Retrying in {delay:.2f}s. Error: {e}", file=sys.stderr)
                time.sleep(delay)
            else:
                print(f"[CRITICAL] API call failed after {MAX_RETRIES} attempts. Giving up. Error: {e}", file=sys.stderr)
                return None
    return None

# --- Robust Log Block Parser  ---

def parse_log_block(block_lines: list) -> dict:
    """
    Parses a block of log lines generated by the Traffic Generator
    into a structured Python dictionary, with added debug output.

    The expected format is lines like: '"key": "value",'.
    """
    event = {}
    # print(f"\n[DEBUG PARSE] Starting to process {len(block_lines)} lines.", file=sys.stderr)
    
    for line in block_lines:
        line = line.strip()
        if not line:
            continue
            
        # print(f"[DEBUG PARSE] RAW Line: '{line}'", file=sys.stderr)

        # Clean the line: remove leading/trailing quotes and the trailing comma
        # We assume the line looks like: "key": "value",
        line_cleaned_comma = line.rstrip(',')
        # print(f"[DEBUG PARSE] Line after comma strip: '{line_cleaned_comma}'", file=sys.stderr)

        # Split on the first colon to separate key and value
        try:
            # Use split(':', 1) to safely handle values that might contain colons 
            key_part, value_part = line_cleaned_comma.split(':', 1)
            # print(f"[DEBUG PARSE] Key Part: '{key_part}', Value Part: '{value_part}'", file=sys.stderr)
        except ValueError:
            # Handle lines that don't conform
            # print(f"[DEBUG PARSE] Warning: Skipping malformed line in block: {line}. No colon found.", file=sys.stderr)
            continue
            
        # Clean up the key and value: remove surrounding quotes and extra whitespace
        # Key cleanup: remove surrounding quotes if present
        key = key_part.strip().strip('"')
        
        # Value cleanup: remove surrounding quotes if present
        value = value_part.strip().strip('"')
        
        # print(f"[DEBUG PARSE] Final Key: '{key}', Final Value: '{value}'", file=sys.stderr)

        # Attempt to cast timestamp to integer if present, otherwise store as string
        if key == 'timestamp':
            try:
                event[key] = int(value)
            except ValueError:
                event[key] = value # Keep as string if conversion fails
        else:
            event[key] = value
            
    # Check for a mandatory field to confirm successful parsing
    if 'module' in event and event['module'] == 'INGESTION_AGENT':
        #print(f"[DEBUG PARSE] SUCCESS. Parsed Event: {json.dumps(event)}", file=sys.stderr)
        return event

    print(f"[DEBUG PARSE] FAILURE. Required field 'module' missing or wrong value. Final dict keys: {list(event.keys())}", file=sys.stderr)
    return {}


# --- Agent 1: Triage & Anomaly Agent (The Filter) ---

class TriageAgent:
    """
    Agent 1: Establishes a basic baseline and filters events before passing 
    them to the specialized expert agents (MITRE/OWASP).
    """
    NORMAL_READ_ACTIONS = [
        "Read Coils (0x01)", 
        "Read Holding Registers (0x03)", 
        "Ack_Data (Response)",
        "DNP3 Frame Detected",
        "PN-IO RT Cyclic Data"
    ]

    def __init__(self):
        print("[*] TriageAgent initialized. Starting baseline checks.")

    def check_for_anomaly(self, event: Dict[str, Any]) -> bool:
        """
        Analyzes an event and returns True if it's a significant anomaly 
        that requires expert analysis (Agents 2/3).
        """
        command_type = event.get("type", "")
        
        # Rule 1: Flag all control commands immediately
        if "CONTROL ACTION" in command_type or command_type in ["Userdata", "Job Request"]:
            event["anomaly_reason"] = "Direct Control Command/Write Action"
            return True

        # Rule 2: Flag unknown or suspicious reconnaissance traffic
        if "Unknown" in command_type or "RECONNAISSANCE" in command_type:
            event["anomaly_reason"] = "Suspicious Reconnaissance or Unknown Protocol Action"
            return True

        # Rule 3: Allow normal read traffic to pass through (Noise Reduction)
        if command_type in self.NORMAL_READ_ACTIONS:
            return False
            
        # Default: If it's not a known normal read action, treat it as an anomaly
        event["anomaly_reason"] = "Non-Baseline/Uncategorized Traffic"
        return True

# --- Agent 2: MITRE ATT&CK for ICS Agent (The Industrial Reasoner) ---

class MITREAgent:
    """
    Agent 2: Uses Gemini to perform contextual reasoning and map network anomalies
    to MITRE ATT&CK for ICS techniques (T-numbers).
    """
    SYSTEM_PROMPT = (
        "You are an expert industrial control systems (ICS) threat intelligence analyst. "
        "Your task is to analyze a raw network anomaly detected by an OT agent and map it "
        "to the most relevant MITRE ATT&CK for ICS Technique (T-number). "
        "The analysis must be based on the provided event data and your domain knowledge."
        "Provide a concise, single-paragraph analysis focusing only on the most plausible technique. "
        "Your final output MUST be in the following JSON format ONLY, without any other preceding or concluding text:\n"
        '{\n'
        '   "mitre_technique": "TXXXX.XX",\n'
        '   "technique_name": "Technique Name",\n'
        '   "plausible_phase": "Phase of Attack (e.g., Impact, Command and Control)",\n'
        '   "analysis_summary": "Concise justification for the mapping (1-2 sentences)."\n'
        '}'
    )

    def __init__(self):
        print("[*] MITREAgent initialized. Ready to perform LLM-based reasoning.")

    def perform_analysis(self, event: Dict[str, Any]) -> Optional[Dict[str, str]]:
        """
        Calls the Gemini API to analyze the event and return a structured MITRE mapping.
        """
        print(f"[*] Calling Gemini for MITRE analysis...")
        
        # Craft the user query with the raw event data
        user_query = (
            f"Analyze the following high-priority ICS anomaly event:\n"
            f"**Anomaly Reason:** {event['anomaly_reason']}\n"
            f"**Protocol:** {event.get('protocol', 'Unknown')}\n"
            f"**Action/Type:** {event.get('type', 'Unknown')}\n"
            f"**Source IP:** {event.get('src', 'N/A')} -> **Destination IP:** {event.get('dst', 'N/A')}\n"
            f"**Payload Snippet (Hex):** {event.get('payload_snippet', 'No Data')}\n\n"
            f"Based on this data, identify the single most likely MITRE ATT&CK for ICS Technique (T-number)."
        )

        payload = {
            "contents": [{"parts": [{"text": user_query}]}],
            "systemInstruction": {"parts": [{"text": self.SYSTEM_PROMPT}]},
            # Request a structured JSON response
            "generationConfig": {
                "responseMimeType": "application/json",
                "responseSchema": {
                    "type": "OBJECT",
                    "properties": {
                        "mitre_technique": {"type": "STRING", "description": "The specific T-number, e.g., T0807."},
                        "technique_name": {"type": "STRING", "description": "The formal name of the technique."},
                        "plausible_phase": {"type": "STRING", "description": "The stage of the attack lifecycle."},
                        "analysis_summary": {"type": "STRING", "description": "A brief explanation of why this technique is plausible."}
                    },
                    "required": ["mitre_technique", "technique_name", "plausible_phase", "analysis_summary"]
                }
            }
        }
        
        response_json = call_gemini_api(payload)
        
        if response_json and response_json.get('candidates'):
            try:
                # The response text should be the JSON string
                json_string = response_json['candidates'][0]['content']['parts'][0]['text']
                # Parse the JSON string into a Python dictionary
                parsed_analysis = json.loads(json_string)
                return parsed_analysis
            except (json.JSONDecodeError, KeyError) as e:
                print(f"[LLM PARSE ERROR] MITRE failed to parse JSON response: {e}", file=sys.stderr)
                return None
        return None

# --- Agent 3: OWASP Agent (The IT/Web Expert) ---

class OWASPAgent:
    """
    Agent 3: Uses Gemini to perform contextual reasoning and map network anomalies
    to relevant OWASP Top 10 categories, focusing on the IT/OT convergence layer.
    """
    SYSTEM_PROMPT = (
        "You are an expert web application security analyst focused on IT/OT convergence points (like HMIs and IIoT gateways). "
        "Your task is to analyze a raw network anomaly event. Determine if the payload or context suggests an attack "
        "that maps to the OWASP Top 10 list (e.g., Injection, Broken Access Control)."
        "Provide a concise, single-paragraph analysis, focusing on whether this is likely a web-based attack and why."
        "If it is clearly an industrial protocol (e.g., Modbus), state that it is not applicable to web security and provide the default technique mapping."
        "Your final output MUST be in the following JSON format ONLY:\n"
        '{\n'
        '   "owasp_category": "AXX:YYYY - Category Name",\n'
        '   "is_web_attack": false,\n'
        '   "analysis_summary": "Concise justification for the mapping (1-2 sentences)."\n'
        '}'
    )

    def __init__(self):
        print("[*] OWASPAgent initialized. Ready to perform LLM-based web security reasoning.")

    def perform_analysis(self, event: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """
        Calls the Gemini API to analyze the event and return a structured OWASP mapping.
        """
        print(f"[*] Calling Gemini for OWASP analysis...")
        
        user_query = (
            f"Analyze the following high-priority ICS anomaly event:\n"
            f"**Anomaly Reason:** {event['anomaly_reason']}\n"
            f"**Protocol:** {event.get('protocol', 'Unknown')}\n"
            f"**Action/Type:** {event.get('type', 'Unknown')}\n"
            f"**Source IP:** {event.get('src', 'N/A')} -> **Destination IP:** {event.get('dst', 'N/A')}\n"
            f"**Payload Snippet (Hex):** {event.get('payload_snippet', 'No Data')}\n\n"
            f"Based on the protocol and payload, is this activity related to a web application vulnerability (OWASP)? Pay close attention to the raw hex payload for signs of injection (e.g., unusual ASCII strings)."
        )

        payload = {
            "contents": [{"parts": [{"text": user_query}]}],
            "systemInstruction": {"parts": [{"text": self.SYSTEM_PROMPT}]},
            # Request a structured JSON response
            "generationConfig": {
                "responseMimeType": "application/json",
                "responseSchema": {
                    "type": "OBJECT",
                    "properties": {
                        "owasp_category": {"type": "STRING", "description": "The relevant OWASP Top 10 category, e.g., A03:2021 - Injection. If non-applicable, use 'A00: None'."},
                        "is_web_attack": {"type": "BOOLEAN", "description": "True if this event is highly likely a web/IT-based attack, False otherwise."},
                        "analysis_summary": {"type": "STRING", "description": "A brief explanation of the web security relevance or lack thereof."}
                    },
                    "required": ["owasp_category", "is_web_attack", "analysis_summary"]
                }
            }
        }
        
        response_json = call_gemini_api(payload)
        
        if response_json and response_json.get('candidates'):
            try:
                json_string = response_json['candidates'][0]['content']['parts'][0]['text']
                parsed_analysis = json.loads(json_string)
                return parsed_analysis
            except (json.JSONDecodeError, KeyError) as e:
                print(f"[LLM PARSE ERROR] OWASP failed to parse JSON response: {e}", file=sys.stderr)
                return None
        return None


# --- Central Orchestrator Functions ---

def display_analysis(event: Dict[str, Any], mitre_report: Dict[str, str], owasp_report: Dict[str, Any]):
    """Formats and prints the final report to stdout for the user/next step."""
    
    print("\n" + "="*80)
    print(f"!!! CRITICAL ANOMALY DETECTED & DUAL-ANALYZED !!!".center(80))
    print("="*80)
    print(f"| REASON: {event.get('anomaly_reason', 'N/A')}")
    print(f"| PROTOCOL: {event.get('protocol', 'N/A')} ({event.get('type', 'N/A')})")
    print(f"| TRAFFIC: {event.get('src', 'N/A')} -> {event.get('dst', 'N/A')}")
    print("-" * 80)
    
    # MITRE Analysis Results (ICS Expert)
    print(f"| MITRE ATT&CK for ICS Mapping:")
    print(f"|   TECHNIQUE: {mitre_report.get('mitre_technique', 'N/A')} - {mitre_report.get('technique_name', 'N/A')}")
    print(f"|   PHASE: {mitre_report.get('plausible_phase', 'N/A')}")
    print(f"|   SUMMARY: {mitre_report.get('analysis_summary', 'N/A')}")
    print("-" * 80)

    # OWASP Analysis Results (IT/Web Expert)
    is_web = owasp_report.get('is_web_attack', False)
    print(f"| OWASP Web Security Mapping ({'HIGH RELEVANCE' if is_web else 'LOW RELEVANCE'}):")
    print(f"|   CATEGORY: {owasp_report.get('owasp_category', 'N/A')}")
    print(f"|   SUMMARY: {owasp_report.get('analysis_summary', 'N/A')}")
    print("="*80 + "\n")


def consume_ingestion_stream(triage_agent: TriageAgent, mitre_agent: MITREAgent, owasp_agent: OWASPAgent):
    """
    The main loop that reads event blocks from stdin (piped from the Traffic Generator).
    """
    event_lines: List[str] = []
    print("[*] Orchestrator started. Listening for events on stdin...")
    
    # Read line-by-line indefinitely
    for line in sys.stdin:
        line = line.strip()

        if line == EVENT_DELIMITER:
            # Delimiter found: process the complete event block
            # print(f"[*] Delimiter found. Processing block of {len(event_lines)} lines.", file=sys.stderr)
            parsed_event = parse_log_block(event_lines)
            
            if parsed_event:
                if triage_agent.check_for_anomaly(parsed_event):
                    # --- Anomaly Detected: Hand-off to Expert Agents ---
                    print(f"[*] Anomaly detected: {parsed_event['anomaly_reason']}. Forwarding for dual analysis.", file=sys.stderr)
                    
                    # Call Agent 2 (MITRE Reasoner)
                    mitre_analysis = mitre_agent.perform_analysis(parsed_event)
                    
                    # Call Agent 3 (OWASP Reasoner)
                    owasp_analysis = owasp_agent.perform_analysis(parsed_event)
                    
                    if mitre_analysis and owasp_analysis:
                        display_analysis(parsed_event, mitre_analysis, owasp_analysis)
                    else:
                        print("[!!!] One or both Expert Agents failed to generate a report.", file=sys.stderr)
                        
            else:
                 print("[!!!] Block skipped due to parsing failure or missing required fields.", file=sys.stderr)
                 
            # Reset buffer for the next event
            event_lines = []
        else:
            # Accumulate lines into the current event list
            event_lines.append(line)
            
def main():
    triage_agent = TriageAgent()
    mitre_agent = MITREAgent()
    owasp_agent = OWASPAgent() # Initialize the new agent
    
    # Check if the API key was successfully loaded
    if not API_KEY:
        print("[WARNING] LLM-based analysis is DISABLED because API_KEY could not be loaded.", file=sys.stderr)

    consume_ingestion_stream(triage_agent, mitre_agent, owasp_agent)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nOrchestrator stopped by user.", file=sys.stderr)
        sys.exit(0)
    except Exception as e:
        print(f"\n[FATAL ERROR] Orchestrator crashed: {e}", file=sys.stderr)
        sys.exit(1)